### ISSUE TITLE
Node engine

### ISSUE THREAD

**Issue by goodmind** [joebowbeer/repdeps#4]
error repdeps@0.3.1: The engine "node" is incompatible with this module. Expected version "8.9.4". Got "11.7.0"

**Comment by joebowbeer** [comment]
@goodmind this may be due to this issue with node 11.7.0, fixed in node 11.8.0:

https://github.com/istanbuljs/nyc/issues/973

**Comment by joebowbeer** [comment]
@goodmind I updated chai, nyc and yargs and published version 0.3.2.

I hope this solves the problem.

**Comment by goodmind** [comment]
@joebowbeer, you probably should also remove 
```
"engines": {
    "node": "8.9.4"
  },
```

**Comment by joebowbeer** [comment]
@goodmind doik! I looked for that the first time but didn't see it. Curious that it is building on node 10 now on travis...

I'll do this soon.

**Comment by joebowbeer** [comment]
Fixed in 0.3.3
